# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmDlg.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_confirmDlg(object):
    def setupUi(self, confirmDlg):
        confirmDlg.setObjectName("confirmDlg")
        confirmDlg.resize(480, 320)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(confirmDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.operatorNameLabel = QtWidgets.QLabel(confirmDlg)
        self.operatorNameLabel.setObjectName("operatorNameLabel")
        self.horizontalLayout_6.addWidget(self.operatorNameLabel)
        self.operatorNameHolders4 = QtWidgets.QLabel(confirmDlg)
        self.operatorNameHolders4.setObjectName("operatorNameHolders4")
        self.horizontalLayout_6.addWidget(self.operatorNameHolders4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(18, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.srLabel = QtWidgets.QLabel(confirmDlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.srLabel.setFont(font)
        self.srLabel.setObjectName("srLabel")
        self.horizontalLayout.addWidget(self.srLabel)
        self.selectedReagentLabel = QtWidgets.QLabel(confirmDlg)
        self.selectedReagentLabel.setObjectName("selectedReagentLabel")
        self.horizontalLayout.addWidget(self.selectedReagentLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edLabel = QtWidgets.QLabel(confirmDlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.edLabel.setFont(font)
        self.edLabel.setObjectName("edLabel")
        self.horizontalLayout_3.addWidget(self.edLabel)
        self.expirationDateLabel = QtWidgets.QLabel(confirmDlg)
        self.expirationDateLabel.setObjectName("expirationDateLabel")
        self.horizontalLayout_3.addWidget(self.expirationDateLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saLabel = QtWidgets.QLabel(confirmDlg)
        self.saLabel.setObjectName("saLabel")
        self.horizontalLayout_5.addWidget(self.saLabel)
        self.weightedAmountLabel = QtWidgets.QLabel(confirmDlg)
        self.weightedAmountLabel.setObjectName("weightedAmountLabel")
        self.horizontalLayout_5.addWidget(self.weightedAmountLabel)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(18, 36, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.acceptPushButton = QtWidgets.QPushButton(confirmDlg)
        self.acceptPushButton.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.acceptPushButton.setFont(font)
        self.acceptPushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.acceptPushButton.setAutoFillBackground(False)
        self.acceptPushButton.setObjectName("acceptPushButton")
        self.horizontalLayout_7.addWidget(self.acceptPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.reweightPushButton = QtWidgets.QPushButton(confirmDlg)
        self.reweightPushButton.setMinimumSize(QtCore.QSize(0, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.reweightPushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.reweightPushButton.setFont(font)
        self.reweightPushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.reweightPushButton.setObjectName("reweightPushButton")
        self.horizontalLayout_7.addWidget(self.reweightPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cLabel = QtWidgets.QLabel(confirmDlg)
        self.cLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cLabel.setObjectName("cLabel")
        self.horizontalLayout_9.addWidget(self.cLabel)
        self.countdownLabel = QtWidgets.QLabel(confirmDlg)
        self.countdownLabel.setObjectName("countdownLabel")
        self.horizontalLayout_9.addWidget(self.countdownLabel)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.logoLabel = QtWidgets.QLabel(confirmDlg)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/Icons/uflogo.png"))
        self.logoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_2.addWidget(self.logoLabel)
        self.logoLabel.raise_()

        self.retranslateUi(confirmDlg)
        QtCore.QMetaObject.connectSlotsByName(confirmDlg)

    def retranslateUi(self, confirmDlg):
        _translate = QtCore.QCoreApplication.translate
        confirmDlg.setWindowTitle(_translate("confirmDlg", "Reagents and hardware - Confirmation"))
        self.operatorNameLabel.setText(_translate("confirmDlg", "Оператор:"))
        self.operatorNameHolders4.setText(_translate("confirmDlg", "NA (не доступно)"))
        self.srLabel.setText(_translate("confirmDlg", "<html><head/><body><p><span style=\" font-weight:600;\">Вибраний реагент:</span></p></body></html>"))
        self.selectedReagentLabel.setText(_translate("confirmDlg", "NA (не доступно)"))
        self.edLabel.setText(_translate("confirmDlg", "Термін придатності:"))
        self.expirationDateLabel.setText(_translate("confirmDlg", "NA (не доступно)"))
        self.saLabel.setText(_translate("confirmDlg", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Відібрана наважка:</span></p></body></html>"))
        self.weightedAmountLabel.setText(_translate("confirmDlg", "<html><head/><body><p><span style=\" font-size:10pt;\">NA (не доступно)</span></p></body></html>"))
        self.acceptPushButton.setToolTip(_translate("confirmDlg", "<html><head/><body><p><span style=\" font-weight:400;\">Натисніть, щоб підтвердити використання реактиву! </span>Зміни будуть внесені в базу даних!</p></body></html>"))
        self.acceptPushButton.setText(_translate("confirmDlg", "Підтвердити"))
        self.reweightPushButton.setToolTip(_translate("confirmDlg", "<html><head/><body><p>Натисніть, щоб повторити процедуру зважування! Вам буде запропоновано вибрати причину необхідності переважування!</p></body></html>"))
        self.reweightPushButton.setText(_translate("confirmDlg", "Переважити"))
        self.cLabel.setText(_translate("confirmDlg", "До автоматичного завершення операції:"))
        self.countdownLabel.setText(_translate("confirmDlg", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">NA</span></p></body></html>"))

import reagentterminal_rc
